---
title: "FML Assignment 4"
author: "Dikshna Kathuri"
date: "2023-11-12"
output:
  pdf_document: default
  html_document: default
---
```{r}
Pharmaceuticals <- read.csv("C:/Users/manus/OneDrive/Desktop/FML ASSIGNMENTS/FML 4/Pharmaceuticals.csv")
```

```{r}
library(tidyverse)
```

```{r}
library(factoextra)
```

```{r}
library(dplyr)
library(ggplot2)
library(cluster)
```

```{r}
Pharma_data <- na.omit(Pharmaceuticals) 

Pharma_data
```

```{r}
#1
#Use only the numerical variables (1 to 9) to cluster the 21 firms. Justify the various choices made in conducting the cluster analysis, such as weights for different variables, the specific clustering algorithm(s) used, the number of clusters formed, and so on.

```

```{r}
#Taking the quantitative variables(1-9) to cluster the 21 firms
row.names(Pharma_data)<- Pharma_data[,1]
Pharma_data1<- Pharma_data[,3:11]
# Considering only numerical values 3-11 columns.
head(Pharma_data1)
```

```{r}
#Normalizing the data frame 
Pharma_data2<-scale(Pharma_data1)
head(Pharma_data2)
```

```{r}
#Determining the number of clusters to do the cluster analysis using Elbow Method
fviz_nbclust(Pharma_data2, kmeans, method = "wss")
```

```{r}
#Observing the above graph from Elbow method, we can see that the graph is not clear to choose k=2 or 3 or 4 or 5. Silhouette method for determining no. of clusters

fviz_nbclust(Pharma_data2, kmeans, method = "silhouette")

```

```{r}
#Applying K-means clustering 
set.seed(64060)
k_5<- kmeans(Pharma_data2,centers=5,nstart = 25)
```

```{r}
#Visualizing the output
#centroids
k_5$centers
```

```{r}
#Visualizing the clusters
fviz_cluster(k_5,data = Pharma_data2) 
```

```{r}
k_5
```

```{r}
distance<- dist(Pharma_data2, method = "euclidean")
fviz_dist(distance)
```

```{r}
#We can see that there are 5 clusters and the center is defined after 25 restarts which is determined in k - means. K - Means Cluster Analysis Fit the data with 5 clusters
fit<-kmeans(Pharma_data2,5)
```


```{r}
#Finding the mean value of all quantitative variables for each cluster
aggregate(Pharma_data2,by=list(fit$cluster),FUN=mean)

```

```{r}
#To view the cluster plot
clusplot(Pharma_data2,fit$cluster,color =
           TRUE,shade = TRUE,labels = 2,lines = 0)

```

```{r}
#2
#Interpret the clusters in light of the numerical variables that were utilised to create them.

#Cluster 1 - AGN, PHA, BAY - These have the highest PE_Ratio. By observing the mean values of all quantitative variables for each cluster. The ROE value is poor.
#JNJ, MRK, GSK, and PFE are in Cluster_2 and have the biggest market capitalization and good leverage value.
#AHM, AVE, and WPI are in Cluster_3, they have the lowest beta and asset turnover.
#Cluster 4: The lowest market capitalization, leverage, and beta are exhibited by IVX, MRX, ELN, and CHTT.
#They're good. Its revenue growth is the highest.
#Cluster 5: ABT, NVS, AZN, LLY, BMY, WYE, SGP - These companies have the largest net profit margin, the biggest asset turnover, and the lowest sales growth.

#Do the clusters exhibit any patterns in relation to the numerical variables (10–12)? (those not utilized in cluster formation)

#For cluster 1: It should be held in accordance with media recommendations as it has the highest PE Ratio.
#For cluster 2: It has a good leverage value and the largest market capitalization. Additionally, they can be rather violent.
#For cluster 3: Its beta and asset turnover are the lowest. However, media endorsements are very positive.
#For cluster 4: They come with a modest recommendation despite the high leverage ratio.
#For Cluster 5: They have the largest net profit margin, the highest asset turnover, and the lowest revenue growth.


#3
#Provide an appropriate name for each cluster using any or all of the variables in the dataset.
#Cluster 1: Hold cluster
#Cluster 2: Mild Purchase or Hold a cluster.
#Cluster 3: Purchase or Sell
#Cluster 4: Purchase Cluster
#Cluster 5: High Hold Cluster
```
